GET http://localhost:3001/api/notes/5c41c90e84d891c15dfa3431

###
POST http://localhost:3001/api/notes HTTP/1.1
Content-type: application/json

{
    
    "content": "Hey there👋",
    "important": true,
    "userId":"63ea461a790e575df6f9f2a1"
  }


###
DELETE http://localhost:3001/api/notes/63d932a4302f18cd1a055b5a


